import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { PHProvider, PostHogPageview } from "./providers";
import { Suspense } from "react";

const mondwest = localFont({
  src: "../public/fonts/PPMondwest-Regular.woff2",
  variable: "--font-mondwest",
});

const inter = localFont({
  src: "../public/fonts/InterVariable.woff2",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Suspense>
        <PostHogPageview />
      </Suspense>
      <PHProvider>
        <body className={`${inter.variable} ${mondwest.variable}`}>
          {children}
        </body>
      </PHProvider>
    </html>
  );
}
